# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Dossier Documentaire EMC
copyright: Copyright &copy; 2023 Damien Hasenfratz
extra:
  generator: false
theme:
  palette:
    primary: green
  language: fr
  features:
    - toc.integrate
    - toc.follow
    - navigation.indexes
    - content.tooltips
    - navigation.footer
  name: material
  icon:
    logo: material/earth
plugins: []
markdown_extensions:
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - md_in_html
  - attr_list
  - footnotes
  - abbr
